### ISSUE TITLE
UnknownError: unknown error: unrecognized Blink revision

### ISSUE THREAD

**Issue by sunil2903** [afternoon/protractor-browsermob-test#5]
Hi Guys,

I have cloned this project into my laptop and installed the required npm's.
I am running both selenium and browsermob-proxy.

when I run npm test

I am getting this error

/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/atoms/error.js:109
  var template = new Error(this.message);
                 ^
UnknownError: unknown error: unrecognized Blink revision: a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b
  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.13.4 x86_64)
    at new bot.Error (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
    at Object.bot.response.checkResponse (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:134:24
    at /Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/webdriver/promise.js:1539:20)
    at notify (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/webdriver/promise.js:362:12)
    at notifyAll (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/webdriver/promise.js:331:7)
    at resolve (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/webdriver/promise.js:309:7)
    at fulfill (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/webdriver/promise.js:429:5)
    at /Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:49)
    at Function.webdriver.WebDriver.createSession (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:111:30)
    at Object.createDriver (/Users/Sunil/protractor-browsermob-test/node_modules/selenium-webdriver/chrome.js:460:30)
    at ChromeDriverProvider.getDriver (/Users/Sunil/protractor-browsermob-test/node_modules/protractor/lib/driverProviders/chrome.js:67:27)
    at /Users/Sunil/protractor-browsermob-test/node_modules/protractor/lib/runner.js:241:41
    at _fulfilled (/Users/Sunil/protractor-browsermob-test/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/Sunil/protractor-browsermob-test/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/Sunil/protractor-browsermob-test/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/Sunil/protractor-browsermob-test/node_modules/protractor/node_modules/q/q.js:573:44
npm ERR! Test failed.  See above for more details.

What changes i have to make in this project to work in my laptop and to capture the network traffic.  Please help me on this.

Thanks,
Sunil

**Comment by skullz03** [comment]
I facing the exact same issues. The steps that I followed:- 
1) Clone the project
2) Open in VS code and run npm install
3) webdriver-manager start in cmd
4) npm test

failed with the exact same error as above. Could someone pls help?

**Comment by skullz03** [comment]
> I facing the exact same issues. The steps that I followed:-
> 
> 1. Clone the project
> 2. Open in VS code and run npm install
> 3. webdriver-manager start in cmd
> 4. npm test
> 
> failed with the exact same error as above. Could someone pls help?

I updated the chromedriver, chrome and protractor version. It resolved the issue
